routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});

*/

Route::get('/demo', 'HomeController@show_demo');

Route::get('/locale/{locale}', function($locale){
    
    Session::put('locale', $locale);
    return response()->json(['msg' => $locale], 200);
    //return back();
});

Route::get('/resend/code', 'user\UserController@resend_code')->name('resend.code');
Route::get('/', 'WelcomeController@check_auth');
Route::post('/visitor/search', 'WelcomeController@visitor_search')->name('visitor.search');
Route::get('/visitor/showdetails/{id}', 'WelcomeController@visitor_showdetails')->name('visitor.showdetails');

Route::get('/candidate/details/{id}', 'user\UserController@candidate_details')->name('candidate.details');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/religion/{id}', 'user\UserController@religion_casste')->name('profile.religion')->middleware('upc');

Route::group(['as'=>'user.', 'prefix'=> 'user', 'namespace' => 'user', 'middleware' => ['auth']], function(){
    Route::get('/profile/create', 'UserController@create_profile')->name('profile.create')->middleware('upc');
    Route::post('/profile/create1', 'UserController@store_profile_first')->name('profile.create1')->middleware('upc');    
    Route::post('/profile/create2', 'UserController@store_profile_second')->name('profile.create2')->middleware('upc');
    Route::post('/profile/create3', 'UserController@store_profile_third')->name('profile.create3')->middleware('upc');
    
    Route::get('/view/profile', 'UserProfileUpdateController@index')->name('view.profile')->middleware('user');

    Route::get('/dashboard', 'UserController@index')->name('dashboard')->middleware('user');
    
    Route::get('/query', 'UserController@query')->name('query')->middleware('user');
    Route::get('/choice/create', 'ChoiceController@create')->name('choice.create')->middleware('user');
    Route::post('/choice/store', 'ChoiceController@store')->name('choice.store')->middleware('user');
    Route::get('/choice/show/{id}', 'ChoiceController@show')->name('choice.show')->middleware('user');
    Route::get('/choice/edit/{id}', 'ChoiceController@edit')->name('choice.edit')->middleware('user');
    Route::post('/choice/update/{id}', 'ChoiceController@update')->name('choice.update')->middleware('user');
    Route::get('/candidate/profile', 'CandidateProfileController@index')->name('candidate.profile')->middleware('user');
    Route::get('/candidate/details/{id}', 'CandidateProfileController@details')->name('candidate.details')->middleware('user');

    Route::get('/verification', 'UserVerificationController@index')->name('verification')->middleware('verification');
    Route::post('/verified', 'UserVerificationController@user_verification')->name('verified')->middleware('verification');
    Route::get('/resend/code', 'UserVerificationController@resend_code')->name('resend.code')->middleware('verification');

    Route::get('/chat', 'ChatController@index')->name('chat')->middleware('user');
    Route::get('/message/{id}', 'ChatController@message')->name('message')->middleware('user');
    Route::get('/view/name/{id}', 'ChatController@view_name')->name('view.name')->middleware('user');
    Route::post('/send/message', 'ChatController@send_message')->name('send.message')->middleware('user');
    Route::get('/unread/message', 'ChatController@unread_message')->name('unread.message')->middleware('user');
    Route::get('/delete/message/{id}', 'ChatController@destroy')->name('delete.message')->middleware('user');

    Route::get('/send-chat-request/{id}', 'ChatRequestController@index')->name('send.chat.request')->middleware('user');

    Route::get('/notifications', 'ChatRequestController@notifications')->name('notifications')->middleware('user');
    Route::get('/notifications/view', 'ChatRequestController@notification_details')->name('notifications.view')->middleware('user');
    //Route::get('/chatrequest/denied/{id}', 'ChatRequestController@denied_request')->name('chatrequest.denied')->middleware('user');
    Route::get('/accept/request/{id}', 'ChatRequestController@accept_request')->name('accept.request')->middleware('user');
    Route::get('/denied/request/{id}', 'ChatRequestController@denied_request')->name('denied.request')->middleware('user');

    Route::get('/add-to-favourite/{id}', 'FavouriteController@create')->name('addToFavourite')->middleware('user');
    Route::get('/favourite/list', 'FavouriteController@index')->name('favourite.list')->middleware('user');
    Route::get('/delete/favourite/{id}', 'FavouriteController@destroy')->name('delete.favourite')->middleware('user');
});

resources/views/pertials/fontend/default-js.blade.php
<script src="{{url('assets/js/vendor/jquery-2.2.4.min.js')}}"></script>
<script src="{{url('assets/js/popper.min.js')}}"></script>
<script src="{{url('assets/js/vendor/bootstrap.min.js')}}"></script>
<script src="https://maps.googleapis.com/maps/api/js?key=AIzaSyBhOdIF3Y9382fqJYt5I_sswSrEw5eihAA"></script>
<script src="{{url('assets/js/easing.min.js')}}"></script>
<script src="{{url('assets/js/hoverIntent.js')}}"></script>
<script src="{{url('assets/js/superfish.min.js')}}"></script>
<script src="{{url('assets/js/jquery.ajaxchimp.min.js')}}"></script>
<script src="{{url('assets/js/jquery.magnific-popup.min.js')}}"></script>
<script src="{{url('assets/js/owl.carousel.min.js')}}"></script>
<script src="{{url('assets/js/jquery.sticky.js')}}"></script>
<script src="{{url('assets/js/jquery.nice-select.min.js')}}"></script>
<script src="{{url('assets/js/parallax.min.js')}}"></script>
<script src="{{url('assets/js/mail-script.js')}}"></script>
<script src="{{url('assets/js/bootstrap-datepicker.js')}}"></script>
<script src="{{url('assets/js/main.js')}}"></script>
<script async src="https://www.googletagmanager.com/gtag/js?id=UA-23581568-13" type="38d45c5b43721184da46bd14-text/javascript"></script>
<script type="38d45c5b43721184da46bd14-text/javascript">
    window.dataLayer = window.dataLayer || [];
    function gtag(){dataLayer.push(arguments);}
    gtag('js', new Date());

    gtag('config', 'UA-23581568-13');
</script>
<script src="{{url('assets/js/rocket-loader.min.js')}}" data-cf-settings="38d45c5b43721184da46bd14-|49" defer=""></script>
<script type="text/javascript">
    
    //on select hide and show
    $(function () {
        
        //Search Hide and show
        $(".search-btn").click(function() {
            $(".search-box").hide();
            $(".target").slideToggle("slow");
        });
        $(".search-input-box").click(function() {
            $(".search-box").hide();
            $(".target").slideToggle("slow");
        });
        //Search Hide and show
        
        
        
    });
    //on select hide and show
            
</script>

<script src="http://cdn.bootcss.com/toastr.js/latest/js/toastr.min.js"></script>
{!! Toastr::message() !!}

<script>
    @if($errors->any())
        @foreach($errors->all() as $error)
        toastr.error('{{ $error }}', 'Error', {
                "closeButton": true,
                "progressBar": true
        });
        
        @endforeach
        $(window).on('load',function(){
        var form1Id = sessionStorage.getItem('form1');
        var form2Id = sessionStorage.getItem('form2');
        console.log(form1Id);
        console.log(form2Id);

        if(form1Id != null && form1Id == 'form1'){
            $('#login_modal').modal('show');
        }

        if(form2Id != null && form2Id == 'form2'){
            $('#register_modal').modal('show');
        }
          
    });
@endif
</script>
<script>
    $('#for-whome').change(function(){      
        $('.select-gender').show("slow");
        var whome = $(this).val(); 
        var $setgender = $('#set-gender');
        $setgender.empty();
        if(whome == 1){                      
            $setgender.html('<option value="male">Male</option><option value="female">Female</option>');        
            $setgender.niceSelect('update');
        }else if(whome == 2 || whome == 4){            
            $setgender.html('<option value="male" selected >Male</option>');
            $setgender.niceSelect('update');
        }else if(whome == 3 || whome == 5){            
            $setgender.html('<option value="female" selected >Female</option>');
            $setgender.niceSelect('update');
        }else{            
            $setgender.html('<option value="male">Male</option><option value="female">Female</option>');
            $setgender.niceSelect('update');        
        }
    });
</script>
<script>
    function hidelogin(){
        $('#login_modal').modal('toggle');
    }

    function hideregistration(){
        $('#register_modal').modal('toggle');
    }

    function signin_status(){
        // Check browser support
        if (typeof(Storage) !== "undefined") {
        sessionStorage.clear();
        // Store
        sessionStorage.setItem("form1", "form1");
        }
    }

    function signup_status(){
        // Check browser support
        if (typeof(Storage) !== "undefined") {
        sessionStorage.clear();
        // Store
        sessionStorage.setItem("form2", "form2");
        }
    }
</script>

<script>
    $('#select-locale').change(function(){
        var selectLocale = $('#select-locale').val();
        var url = "{{url('/locale')}}/" + selectLocale;
        console.log(url);

        $.ajax({
            url:url,
            method:'GET',
        }).done(function(data){
            console.log(data.msg);
            if(data.msg == 'bn'){
                $("#bangla").attr("selected",true);
                $("#english").attr("selected",false);
            }else{
                $("#bangla").attr("selected",false);
                $("#english").attr("selected",true);
            }
            location.reload(true);
        });
    });
</script>

resources/views/pertials/fontend/footer.blade.php
<div class="container">
        <div class="row">
            <div class="col-lg-6  col-md-12">
                <div class="single-footer-widget newsletter">
                <h6>{{trans('welcome.why_us')}}</h6>
                    <p>“Recently, the US Federal government banned online casinos from operating in America by making it illegal to transfer money to them through any US bank or payment system. As a result of this law, most of the popular online casino networks such as Party Gaming and PlayTech left the United States. Overnight, online casino players found themselves being chased by the Federal government.</p>
                </div>
            </div>
            <div class="col-lg-3  col-md-12">
                <div class="single-footer-widget">
                <h6>{{trans('welcome.need_help')}}</h6>
                    <ul class="footer-nav">
                        <li><a href="#">Member LogIn</a></li>
                        <li><a href="#">Sign Up</a></li>
                        <li><a href="#">Advanched Search</a></li>
                        <li><a href="#">Success Stories</a></li>
                    </ul>
                </div>
            </div>
            <div class="col-lg-3  col-md-12">
                <div class="single-footer-widget mail-chimp">
                    <h6 class="mb-20">New Member ...</h6>
                    <ul class="instafeed d-flex flex-wrap">
                        <li><a href="#"><img src="{{url('assets/img/i1.jpg')}}" alt=""></a></li>
                        <li><a href="#"><img src="{{url('assets/img/i2.jpg')}}" alt=""></a></li>
                        <li><a href="#"><img src="{{url('assets/img/i3.jpg')}}" alt=""></a></li>
                        <li><a href="#"><img src="{{url('assets/img/i4.jpg')}}" alt=""></a></li>
                        <li><a href="#"><img src="{{url('assets/img/i5.jpg')}}" alt=""></a></li>
                        <li><a href="#"><img src="{{url('assets/img/i6.jpg')}}" alt=""></a></li>
                    </ul>
                </div>
            </div>
        </div>
        <div class="row footer-bottom d-flex justify-content-between">
            <p class="col-lg-8 col-sm-12 footer-text m-0 text-white">
            Copyright &copy;<script type="38d45c5b43721184da46bd14-text/javascript">document.write(new Date().getFullYear());</script> All rights reserved by <a href="http://www.bigweb.com.bd/" target="_blank">Big Web Technologies Ltd.</a>
            </p>
        </div>
    </div>

resources/views/pertials/fontend/head.blade.php
<meta name="viewport" content="width=device-width, initial-scale=1, shrink-to-fit=no">
<link rel="shortcut icon" href="{{url('assets/img/favicon-16.png')}}">
<meta name="author" content="Mortuja Jahan, S. M. Masud Rana">
<meta name="description" content="">
<meta name="keywords" content="">
<meta charset="UTF-8">
<title>Marriage Matrimony</title>
<!-- CSRF Token -->
<meta name="csrf-token" content="{{ csrf_token() }}">

<link href="https://fonts.googleapis.com/css?family=Roboto:100,200,400,300,500,600,700" rel="stylesheet">
<link href="https://fonts.googleapis.com/css?family=Petit+Formal+Script&display=swap" rel="stylesheet">
<link rel="stylesheet" href="{{url('assets/css/linearicons.css')}}">
<link rel="stylesheet" href="{{url('assets/css/font-awesome.min.css')}}">
<link rel="stylesheet" href="{{url('assets/css/bootstrap.css')}}">
<link rel="stylesheet" href="{{url('assets/css/magnific-popup.css')}}">
<link rel="stylesheet" href="{{url('assets/css/nice-select.css')}}">
<link rel="stylesheet" href="{{url('assets/css/animate.min.css')}}">
<link rel="stylesheet" href="{{url('assets/css/datepicker.css')}}">
<link rel="stylesheet" href="{{url('assets/css/owl.carousel.css')}}">
<link rel="stylesheet" href="{{url('assets/css/main.css')}}">
<link rel="stylesheet" href="http://cdn.bootcss.com/toastr.js/latest/css/toastr.min.css">

resources/views/pertials/fontend/header.blade.php
<header id="header" id="home">
	<div class="container">
		<div class="row align-items-center justify-content-between d-flex">
			<div id="logo">
				<a href="index.html"><img src="{{url('assets/img/logo.png')}}" alt="" title="" /></a>
			</div>
			<nav id="nav-menu-container">											
				<ul class="nav-menu">
					@if (\Request::is('visitor/search'))  
					<li><a class="log-menu" href="{{url('/')}}">{{trans('index.home')}}</a></li>
					@endif
					@if(Auth::user())<li><a class="log-menu" href="{{route('user.dashboard')}}">{{trans('index.menu_item_1')}}</a></li>@endif
					@if(Auth::user())<li><a class="log-menu" href="{{route('user.chat')}}">{{trans('index.menu_item_2')}}</a></li>@endif
					@if(Auth::guest())<li><a class="log-menu" href="#" data-toggle="modal" data-target="#login_modal">{{trans('index.menu_item_3')}} <i class="fa fa-user-circle-o" aria-hidden="true"></i></a></li>@endif
					@if(Auth::user())
						<li>
						<a class="log-menu" 
							href="{{ route('logout') }}" 
							onclick="event.preventDefault();
							document.getElementById('logout-form').submit();">
							{{trans('index.menu_item_4')}}</a>
							<form id="logout-form" action="{{ route('logout') }}" method="POST" style="display: none;">
								@csrf
							</form>
						</li>
					@endif
					@if(Auth::guest())<li><a class="log-menu" href="#" data-toggle="modal" data-target="#register_modal">{{trans('index.menu_item_5')}}</a></li>@endif					
				</ul>
				<select name="locale" id="select-locale" class="language-select-btn">
					<option>Language</option>
					<option id="english" value="en">English</option>
					<option id="bangla" value="bn">বাংলা</option>
				</select>
			</nav>
		</div>
	</div>
</header>

resources/views/pertials/fontend/header_old.blade.php
<div class="container">
    <div class="row align-items-center justify-content-between d-flex">
        <div id="logo">
            <a href="index.html"><img src="{{url('assets/img/logo.png')}}" alt="" title="" /></a>
        </div>
        <ul class="nav-menu">
            <li><a class="log-menu" href="#" data-toggle="modal" data-target="#login_modal">Login <i class="fa fa-user-circle-o" aria-hidden="true"></i></a></li>
            <li><a class="ticker-btn" href="#" data-toggle="modal" data-target="#register_modal">Register Free</a></li>
        </ul>
    </div>
</div>