routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});

*/

Route::get('/demo', 'HomeController@show_demo');

Route::get('/locale/{locale}', function($locale){
    
    Session::put('locale', $locale);
    return response()->json(['msg' => $locale], 200);
    //return back();
});

Route::get('/resend/code', 'user\UserController@resend_code')->name('resend.code');
Route::get('/', 'WelcomeController@check_auth');
Route::post('/visitor/search', 'WelcomeController@visitor_search')->name('visitor.search');
Route::get('/visitor/showdetails/{id}', 'WelcomeController@visitor_showdetails')->name('visitor.showdetails');

Route::get('/candidate/details/{id}', 'user\UserController@candidate_details')->name('candidate.details');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/religion/{id}', 'user\UserController@religion_casste')->name('profile.religion')->middleware('upc');

Route::group(['as'=>'user.', 'prefix'=> 'user', 'namespace' => 'user', 'middleware' => ['auth']], function(){
    Route::get('/profile/create', 'UserController@create_profile')->name('profile.create')->middleware('upc');
    Route::post('/profile/create1', 'UserController@store_profile_first')->name('profile.create1')->middleware('upc');    
    Route::post('/profile/create2', 'UserController@store_profile_second')->name('profile.create2')->middleware('upc');
    Route::post('/profile/create3', 'UserController@store_profile_third')->name('profile.create3')->middleware('upc');
    
    Route::get('/view/profile', 'UserProfileUpdateController@index')->name('view.profile')->middleware('user');

    Route::get('/dashboard', 'UserController@index')->name('dashboard')->middleware('user');
    
    Route::get('/query', 'UserController@query')->name('query')->middleware('user');
    Route::get('/choice/create', 'ChoiceController@create')->name('choice.create')->middleware('user');
    Route::post('/choice/store', 'ChoiceController@store')->name('choice.store')->middleware('user');
    Route::get('/choice/show/{id}', 'ChoiceController@show')->name('choice.show')->middleware('user');
    Route::get('/choice/edit/{id}', 'ChoiceController@edit')->name('choice.edit')->middleware('user');
    Route::post('/choice/update/{id}', 'ChoiceController@update')->name('choice.update')->middleware('user');
    Route::get('/candidate/profile', 'CandidateProfileController@index')->name('candidate.profile')->middleware('user');
    Route::get('/candidate/details/{id}', 'CandidateProfileController@details')->name('candidate.details')->middleware('user');

    Route::get('/verification', 'UserVerificationController@index')->name('verification')->middleware('verification');
    Route::post('/verified', 'UserVerificationController@user_verification')->name('verified')->middleware('verification');
    Route::get('/resend/code', 'UserVerificationController@resend_code')->name('resend.code')->middleware('verification');

    Route::get('/chat', 'ChatController@index')->name('chat')->middleware('user');
    Route::get('/message/{id}', 'ChatController@message')->name('message')->middleware('user');
    Route::get('/view/name/{id}', 'ChatController@view_name')->name('view.name')->middleware('user');
    Route::post('/send/message', 'ChatController@send_message')->name('send.message')->middleware('user');
    Route::get('/unread/message', 'ChatController@unread_message')->name('unread.message')->middleware('user');
    Route::get('/delete/message/{id}', 'ChatController@destroy')->name('delete.message')->middleware('user');

    Route::get('/send-chat-request/{id}', 'ChatRequestController@index')->name('send.chat.request')->middleware('user');

    Route::get('/notifications', 'ChatRequestController@notifications')->name('notifications')->middleware('user');
    Route::get('/notifications/view', 'ChatRequestController@notification_details')->name('notifications.view')->middleware('user');
    //Route::get('/chatrequest/denied/{id}', 'ChatRequestController@denied_request')->name('chatrequest.denied')->middleware('user');
    Route::get('/accept/request/{id}', 'ChatRequestController@accept_request')->name('accept.request')->middleware('user');
    Route::get('/denied/request/{id}', 'ChatRequestController@denied_request')->name('denied.request')->middleware('user');

    Route::get('/add-to-favourite/{id}', 'FavouriteController@create')->name('addToFavourite')->middleware('user');
    Route::get('/favourite/list', 'FavouriteController@index')->name('favourite.list')->middleware('user');
    Route::get('/delete/favourite/{id}', 'FavouriteController@destroy')->name('delete.favourite')->middleware('user');
});

app/Http/Controllers/user/CandidateProfileController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Brian2694\Toastr\Facades\Toastr;
use App\User;
use App\Choice;
use App\Division;
use App\Profile;
use App\District;
use App\Religion;
use App\EmployeType;
use App\Occupation;
use App\IncomeRange;
use DB;

class CandidateProfileController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(){
        $id = Auth::user()->id;
        
        $user = User::where('id', $id)->with('choice', 'profile')->first();

        $choiceDivision = $user->choice->division;
        $religion = $user->profile->religion;
        $choiceHeightFrom = $user->choice->height_from;
        $choiceHeightTo = $user->choice->height_to;
        $choiceAgeFrom = age2dob($user->choice->age_from);
        $choiceAgeTo = age2dob($user->choice->age_to);
        $gender = $user->gender;

        /*
        echo $choiceDivision."<br/>".$religion."<br/>".$choiceHeightFrom."<br/>".$choiceHeightTo. 
        "<br/>".$choiceAgeFrom."<br/>".$choiceAgeTo."<br/>".$gender;
        */
        $selectedCandidates = Profile::where('religion_id', $religion->id)
            ->whereHas('user', function($q) use($gender){
                $q->where('gender', '!=', $gender);
            })
            ->where('division_id', $choiceDivision->id)
            ->whereBetween('height',[$choiceHeightFrom,$choiceHeightTo])
            ->whereBetween('dob',[$choiceAgeTo,$choiceAgeFrom])
            ->with('religion','occupation', 'employe_type', 'income_range')
            ->get();
        /*
        echo "<pre>";
        print_r($selectedCandidates);
        die();
        */
        return view('pages.users.candidate.index',['selectedCandidates' => $selectedCandidates]);
    }



    public function details($id){
        $candidate = Profile::where('id', $id)
        ->with('religion','occupation', 'employe_type', 'income_range')
        ->first();

        return view('pages.users.candidate.show',['candidate' => $candidate]);
    }
}

app/Http/Controllers/user/ChatController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Brian2694\Toastr\Facades\Toastr;
use App\User;
use App\ChatRequest;
use App\Chat;
use App\Profile;

class ChatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id = Auth::id();
        // User::where('id', $id)->update(['login_status' => 1]);

        $users = ChatRequest::where('sender_user_id',$id)
        ->where('status', 1) 
        ->orWhere('receiver_user_id', $id)
        ->where('status', 1)
        ->with('sender_user', 'receiver_user')          
        ->get(); 

        /*
        echo "<pre>";
        print_r($users);
        die();
        */

        return view('pages.chat.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function message($id)
    {
        // echo $id;
        $userId = Auth::id();
        $permission = ChatRequest::where('sender_user_id',$id)
        ->where('receiver_user_id', $userId)
        ->where('status', 1) 
        ->orWhere('receiver_user_id', $id)
        ->where('sender_user_id', $userId)
        ->where('status', 1)
        ->first();

        if($permission){
            $messages = Chat::where('sender_user_id',$id)
            ->where('receiver_user_id', $userId)
            ->orWhere('receiver_user_id', $id)
            ->where('sender_user_id', $userId)
            ->with('sender_user', 'receiver_user')             
            ->get();
            return response()->json(['messages' => $messages], 200);
            
        }else{
            echo "Sorry no data found";
        }
        
    }


    public function view_name($id){
        $userName = Profile::select('full_name', 'image')->where('user_id', $id)->first();
        return response()->json(['userName' => $userName], 200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function send_message(Request $request)
    {
        $userId = Auth::id();
        $receiverId = $request->id;
        $message = $request->message;

        $permission = ChatRequest::where('sender_user_id',$userId)
        ->where('receiver_user_id', $receiverId)
        ->where('status', 1) 
        ->orWhere('receiver_user_id', $userId)
        ->where('sender_user_id', $receiverId)
        ->where('status', 1)
        ->first();

        if($permission){
            $chat = new Chat();
            $chat->sender_user_id = $userId;
            $chat->receiver_user_id = $receiverId;
            $chat->message = $message;
            $chat->created_at = date('Y-m-d');
            $chat->save();
        }
        return response()->json(['message' => $permission], 200); 
        
    }


    public function unread_message(){
        $userId = Auth::id();
        $messages = Chat::where('receiver_user_id',$userId)
            ->where('is_seen', 1) 
            ->distinct('sender_user_id')         
            ->count();
        return response()->json(['messages' => $messages], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleteResult = Chat::find($id)->delete();
        if($deleteResult){
            Toastr::success('Conversation has deleted.', 'success');
            return response()->json(['message' => 'Ok'], 200);
        }
        
    }
}

app/Http/Controllers/user/ChatRequestController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Brian2694\Toastr\Facades\Toastr;
use App\ChatRequest;
use App\User;
use App\Profile;

class ChatRequestController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        $userId = Auth::id();
        $receiverProfileId = (int)$id;

        $receiverId = Profile::select('user_id', 'full_name')->where('id', $id)->first();
    
        $checkRequest = ChatRequest::where('sender_user_id',$userId)
        ->where('receiver_user_id', $receiverId->user_id)
        ->orWhere('receiver_user_id', $userId)
        ->where('sender_user_id', $receiverId->user_id)
        ->first();

        if(is_null($checkRequest)){            
            $chatRequest = new ChatRequest();
            $chatRequest->sender_user_id = $userId;
            $chatRequest->receiver_user_id = $receiverId->user_id;
            $chatRequest->created_at = date('Y-m-d');
            $chatRequest->save();
            addTrail('User has successfully send the chat request to '.$id.'.', 'Success');
            Toastr::success('Your chat request has sent to '.$receiverId->full_name);
            return response()->json(['message' => 'Your chat request has sent to '.$receiverId->full_name], 200);
        }else{                
            if($checkRequest->status == 1){
                Toastr::error('You have already connected with '.$receiverId->full_name);
                return response()->json(['message' => 'You have already connected with '.$receiverId->full_name], 200);
            }else{
                Toastr::error('You have already send the chat request to '.$receiverId->full_name);
                return response()->json(['message' => 'You have already send the chat request to '.$receiverId->full_name], 200);
            }           
            
        }        
    }

    public function notifications(){
        $userId = Auth::id();

        $notifications =  ChatRequest::where('receiver_user_id', $userId)->where('status', 0)->count();

        return response()->json(['notifications' => $notifications], 200);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function notification_details()
    {
        $userId = Auth::id();
        $notifications =  ChatRequest::where('receiver_user_id', $userId)->where('status', 0)->with('sender_user')->paginate(12);
        
        

        return view('pages.chat.request', ['notifications' => $notifications]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function accept_request($id)
    {
        $userId = Auth::id();
        $senderId = Profile::select('user_id', 'full_name')->where('id',$id)->first();

        $update = ChatRequest::where('receiver_user_id', $userId)->where('sender_user_id', $senderId->user_id)->update(['status' => 1]);
        Toastr::success('You have accepted the chat request of '.$senderId->full_name. '. Now you can chat with '.$senderId->full_name);
        return response()->json(['id' => $senderId], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function denied_request($id)
    {
        $userId = Auth::id();
        $senderId = Profile::select('user_id', 'full_name')->where('id',$id)->first();

        $deleteResult = ChatRequest::where('receiver_user_id', $userId)->where('sender_user_id', $senderId->user_id)->delete();

        if($deleteResult){
            Toastr::success('You have denied the chat request of '.$senderId->full_name);
            return response()->json(['success' => 'Ok'], 200);
        }else{
            Toastr::error('Woops!! Something went wrong, try again');
            return response()->json(['success' => 'Ok'], 200);
        }
    }
}

app/Http/Controllers/user/UserProfileUpdateController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Brian2694\Toastr\Facades\Toastr;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;
use App\User;
use App\Choice;
use App\Profile;
use App\Country;
use App\District;
use App\Division;
use App\Religion;
use App\Caste;
use App\MaritalStatus;
use App\BloodGroup;
use App\Immigration;
use App\NRB;
use App\Education;
use App\EmployeType;
use App\Occupation;
use App\IncomeRange;
use App\Employment;
use DB;
use Carbon\Carbon;
use File;

class UserProfileUpdateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $userId = Auth::user()->id;
        $profileId = Profile::select('id')->where('user_id', $userId)->first();
        $profileDetails = Profile::where('id', $profileId->id)
        ->with('country', 'present_district', 'home_district','religion', 'caste', 'occupation', 'employe_type', 'income_range', 'marital_status', 'nrb', 'employment', 'education')
        ->first();
        return view('pages.users.profile.show',['profileDetails' => $profileDetails]);        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/users/profile/profile-create-2.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
    <div class="offset-md-2 col-md-8">
            <div class="card">
                <div class="card-header">{{ __('Create Profile') }}</div>

                <div class="card-body">
                    <form method="POST" action="{{ route('user.profile.create2') }}">
                        @csrf
                        
                        <div class="form-group row">
                            <label for="heigher-education" class="col-md-4 col-form-label text-md-right">{{ __('Heigher Education Label') }}</label>

                            <div class="col-md-6">
                                <select id="heigher-education" class="form-control @error('heigher-education') is-invalid @enderror" name="heigher-education">
                                    @foreach($educations as $education)
                                    <option value="{{ $education->id }}">{{ $education->english_name }}</option>
                                    @endforeach
                                </select>
                                @error('heigher-education')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="institution" class="col-md-4 col-form-label text-md-right">{{ __('Institution') }}</label>

                            <div class="col-md-6">
                                <input id="institution" type="text" class="form-control @error('institution') is-invalid @enderror" name="institution" value="{{ old('institution') }}" autocomplete="institution">

                                @error('institution')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="educational-details" class="col-md-4 col-form-label text-md-right">{{ __('Short Description') }}</label>

                            <div class="col-md-6">
                                <input id="educational-details" type="text" class="form-control @error('educational-details') is-invalid @enderror" name="educational-details" value="{{ old('educational-details') }}" autocomplete="educational-details">

                                @error('educational-details')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="service" class="col-md-4 col-form-label text-md-right">{{ __('Service') }}</label>

                            <div class="col-md-6">                                
                                <select id="service" class="form-control @error('service') is-invalid @enderror" name="service">
                                @foreach($employeTypes as $employeType)
                                <option value="{{ $employeType->id }}">{{ $employeType->english_name }}</option>
                                @endforeach
                                </select>
                                @error('service')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="occupation" class="col-md-4 col-form-label text-md-right">{{ __('Occupation') }}</label>

                            <div class="col-md-6">                                
                                <select id="occupation" class="form-control @error('occupation') is-invalid @enderror" name="occupation">
                                @foreach($occupations as $occupation)
                                <option value="{{ $occupation->id }}">{{ $occupation->english_name }}</option>
                                @endforeach
                                </select>
                                @error('occupation')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="salary-range" class="col-md-4 col-form-label text-md-right">{{ __('Salary Range') }}</label>

                            <div class="col-md-6">                                
                                <select id="salary-range" class="form-control @error('salary-range') is-invalid @enderror" name="salary-range">
                                    @foreach($imcomeRanges as $incomeRange)
                                        <option value="{{ $incomeRange->id }}">{{ $incomeRange->en_range_from }} - {{ $incomeRange->en_range_to }}</option>
                                    @endforeach
                                </select>
                                @error('salary-range')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="employer" class="col-md-4 col-form-label text-md-right">{{ __('Employer') }}</label>

                            <div class="col-md-6">
                                <input id="employer" type="text" class="form-control @error('employer') is-invalid @enderror" name="employer" value="{{ old('employer') }}" autocomplete="employer">

                                @error('employer')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="employer-address" class="col-md-4 col-form-label text-md-right">{{ __('Employer Address') }}</label>

                            <div class="col-md-6">
                                <input id="employer-address" type="text" class="form-control @error('employer-address') is-invalid @enderror" name="employer-address" value="{{ old('employer-address') }}" autocomplete="employer-address">

                                @error('employer-address')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>

                        <div class="form-group row">
                            <label for="position" class="col-md-4 col-form-label text-md-right">{{ __('position') }}</label>

                            <div class="col-md-6">
                                <input id="position" type="text" class="form-control @error('position') is-invalid @enderror" name="position" value="{{ old('position') }}" autocomplete="position">

                                @error('position')
                                    <span class="invalid-feedback" role="alert">
                                        <strong>{{ $message }}</strong>
                                    </span>
                                @enderror
                            </div>
                        </div>            

                        
                        <div class="form-group row mb-0">
                            <div class="col-md-6 offset-md-4">
                                <button type="submit" class="btn btn-primary">
                                    {{ __('Save & Continue') }}
                                </button>
                            </div>
                        </div>
                    </form>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection

resources/views/pages/users/profile/profile-create-3.blade.php
@extends('layouts.app')

@section('content')
<div class="container">
    <div class="row">
            <div class="offset-md-2 col-md-8">
                <div class="card">
                    <div class="card-header">{{ __('Create Profile') }}</div>

                    <div class="card-body">
                        <form method="POST" action="{{ route('user.profile.create3') }}" enctype="multipart/form-data">
                            @csrf
                            
                            

                            <div class="form-group row">
                                <label for="id-proof" class="col-md-4 col-form-label text-md-right">{{ __('Id Proof') }}</label>

                                <div class="col-md-6">
                                    <input id="id-proof" type="file" class="form-control @error('id-proof') is-invalid @enderror" name="id-proof" value="{{ old('id-proof') }}" autocomplete="id-proof">

                                    @error('id-proof')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="profile-image" class="col-md-4 col-form-label text-md-right">{{ __('Profile Image') }}</label>

                                <div class="col-md-6">
                                    <input id="profile-image" type="file" class="form-control @error('profile-image') is-invalid @enderror" name="profile-image" value="{{ old('profile-image') }}" autocomplete="profile-image">

                                    @error('profile-image')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="note" class="col-md-4 col-form-label text-md-right">{{ __('Note') }}</label>

                                <div class="col-md-6">                                
                                <input id="note" type="text" class="form-control @error('note') is-invalid @enderror" name="note" value="{{ old('note') }}" autocomplete="note">
                                    @error('note')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>

                            <div class="form-group row">
                                <label for="verification" class="col-md-4 col-form-label text-md-right">{{ __('Verification Code') }}</label>

                                <div class="col-md-6">                                
                                <input id="verification" type="text" class="form-control @error('verification') is-invalid @enderror" name="verification" value="{{ old('verification') }}" autocomplete="verification">
                                    @error('verification')
                                        <span class="invalid-feedback" role="alert">
                                            <strong>{{ $message }}</strong>
                                        </span>
                                    @enderror
                                </div>
                            </div>      

                            <div class="form-group row mb-0">
                                <div class="col-md-6 offset-md-4">
                                    <button type="submit" class="btn btn-primary">
                                        {{ __('Save') }}
                                    </button>
                                </div>
                            </div>
                        </form>
                    </div>
                </div>
            </div>
        </div>
    </div>
</div>
@endsection