routes/web.php
<?php

/*
|--------------------------------------------------------------------------
| Web Routes
|--------------------------------------------------------------------------
|
| Here is where you can register web routes for your application. These
| routes are loaded by the RouteServiceProvider within a group which
| contains the "web" middleware group. Now create something great!
|
*/
/*
Route::get('/', function () {
    return view('welcome');
});

*/

Route::get('/demo', 'HomeController@show_demo');

Route::get('/locale/{locale}', function($locale){
    
    Session::put('locale', $locale);
    return response()->json(['msg' => $locale], 200);
    //return back();
});

Route::get('/resend/code', 'user\UserController@resend_code')->name('resend.code');
Route::get('/', 'WelcomeController@check_auth');
Route::post('/visitor/search', 'WelcomeController@visitor_search')->name('visitor.search');
Route::get('/visitor/showdetails/{id}', 'WelcomeController@visitor_showdetails')->name('visitor.showdetails');

Route::get('/candidate/details/{id}', 'user\UserController@candidate_details')->name('candidate.details');

Auth::routes();

Route::get('/home', 'HomeController@index')->name('home');
Route::get('/religion/{id}', 'user\UserController@religion_casste')->name('profile.religion')->middleware('upc');

Route::group(['as'=>'user.', 'prefix'=> 'user', 'namespace' => 'user', 'middleware' => ['auth']], function(){
    Route::get('/profile/create', 'UserController@create_profile')->name('profile.create')->middleware('upc');
    Route::post('/profile/create1', 'UserController@store_profile_first')->name('profile.create1')->middleware('upc');    
    Route::post('/profile/create2', 'UserController@store_profile_second')->name('profile.create2')->middleware('upc');
    Route::post('/profile/create3', 'UserController@store_profile_third')->name('profile.create3')->middleware('upc');
    
    Route::get('/view/profile', 'UserProfileUpdateController@index')->name('view.profile')->middleware('user');

    Route::get('/dashboard', 'UserController@index')->name('dashboard')->middleware('user');
    
    Route::get('/query', 'UserController@query')->name('query')->middleware('user');
    Route::get('/choice/create', 'ChoiceController@create')->name('choice.create')->middleware('user');
    Route::post('/choice/store', 'ChoiceController@store')->name('choice.store')->middleware('user');
    Route::get('/choice/show/{id}', 'ChoiceController@show')->name('choice.show')->middleware('user');
    Route::get('/choice/edit/{id}', 'ChoiceController@edit')->name('choice.edit')->middleware('user');
    Route::post('/choice/update/{id}', 'ChoiceController@update')->name('choice.update')->middleware('user');
    Route::get('/candidate/profile', 'CandidateProfileController@index')->name('candidate.profile')->middleware('user');
    Route::get('/candidate/details/{id}', 'CandidateProfileController@details')->name('candidate.details')->middleware('user');

    Route::get('/verification', 'UserVerificationController@index')->name('verification')->middleware('verification');
    Route::post('/verified', 'UserVerificationController@user_verification')->name('verified')->middleware('verification');
    Route::get('/resend/code', 'UserVerificationController@resend_code')->name('resend.code')->middleware('verification');

    Route::get('/chat', 'ChatController@index')->name('chat')->middleware('user');
    Route::get('/message/{id}', 'ChatController@message')->name('message')->middleware('user');
    Route::get('/view/name/{id}', 'ChatController@view_name')->name('view.name')->middleware('user');
    Route::post('/send/message', 'ChatController@send_message')->name('send.message')->middleware('user');
    Route::get('/unread/message', 'ChatController@unread_message')->name('unread.message')->middleware('user');
    Route::get('/delete/message/{id}', 'ChatController@destroy')->name('delete.message')->middleware('user');

    Route::get('/send-chat-request/{id}', 'ChatRequestController@index')->name('send.chat.request')->middleware('user');

    Route::get('/notifications', 'ChatRequestController@notifications')->name('notifications')->middleware('user');
    Route::get('/notifications/view', 'ChatRequestController@notification_details')->name('notifications.view')->middleware('user');
    //Route::get('/chatrequest/denied/{id}', 'ChatRequestController@denied_request')->name('chatrequest.denied')->middleware('user');
    Route::get('/accept/request/{id}', 'ChatRequestController@accept_request')->name('accept.request')->middleware('user');
    Route::get('/denied/request/{id}', 'ChatRequestController@denied_request')->name('denied.request')->middleware('user');

    Route::get('/add-to-favourite/{id}', 'FavouriteController@create')->name('addToFavourite')->middleware('user');
    Route::get('/favourite/list', 'FavouriteController@index')->name('favourite.list')->middleware('user');
    Route::get('/delete/favourite/{id}', 'FavouriteController@destroy')->name('delete.favourite')->middleware('user');
});

app/Http/Controllers/user/CandidateProfileController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Brian2694\Toastr\Facades\Toastr;
use App\User;
use App\Choice;
use App\Division;
use App\Profile;
use App\District;
use App\Religion;
use App\EmployeType;
use App\Occupation;
use App\IncomeRange;
use DB;

class CandidateProfileController extends Controller
{
    /**
     * Create a new controller instance.
     *
     * @return void
     */
    public function __construct()
    {
        $this->middleware('auth');
    }

    public function index(){
        $id = Auth::user()->id;
        
        $user = User::where('id', $id)->with('choice', 'profile')->first();

        $choiceDivision = $user->choice->division;
        $religion = $user->profile->religion;
        $choiceHeightFrom = $user->choice->height_from;
        $choiceHeightTo = $user->choice->height_to;
        $choiceAgeFrom = age2dob($user->choice->age_from);
        $choiceAgeTo = age2dob($user->choice->age_to);
        $gender = $user->gender;

        /*
        echo $choiceDivision."<br/>".$religion."<br/>".$choiceHeightFrom."<br/>".$choiceHeightTo. 
        "<br/>".$choiceAgeFrom."<br/>".$choiceAgeTo."<br/>".$gender;
        */
        $selectedCandidates = Profile::where('religion_id', $religion->id)
            ->whereHas('user', function($q) use($gender){
                $q->where('gender', '!=', $gender);
            })
            ->where('division_id', $choiceDivision->id)
            ->whereBetween('height',[$choiceHeightFrom,$choiceHeightTo])
            ->whereBetween('dob',[$choiceAgeTo,$choiceAgeFrom])
            ->with('religion','occupation', 'employe_type', 'income_range')
            ->get();
        /*
        echo "<pre>";
        print_r($selectedCandidates);
        die();
        */
        return view('pages.users.candidate.index',['selectedCandidates' => $selectedCandidates]);
    }



    public function details($id){
        $candidate = Profile::where('id', $id)
        ->with('religion','occupation', 'employe_type', 'income_range')
        ->first();

        return view('pages.users.candidate.show',['candidate' => $candidate]);
    }
}

app/Http/Controllers/user/ChatController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Brian2694\Toastr\Facades\Toastr;
use App\User;
use App\ChatRequest;
use App\Chat;
use App\Profile;

class ChatController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $id = Auth::id();
        // User::where('id', $id)->update(['login_status' => 1]);

        $users = ChatRequest::where('sender_user_id',$id)
        ->where('status', 1) 
        ->orWhere('receiver_user_id', $id)
        ->where('status', 1)
        ->with('sender_user', 'receiver_user')          
        ->get(); 

        /*
        echo "<pre>";
        print_r($users);
        die();
        */

        return view('pages.chat.index', ['users' => $users]);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function message($id)
    {
        // echo $id;
        $userId = Auth::id();
        $permission = ChatRequest::where('sender_user_id',$id)
        ->where('receiver_user_id', $userId)
        ->where('status', 1) 
        ->orWhere('receiver_user_id', $id)
        ->where('sender_user_id', $userId)
        ->where('status', 1)
        ->first();

        if($permission){
            $messages = Chat::where('sender_user_id',$id)
            ->where('receiver_user_id', $userId)
            ->orWhere('receiver_user_id', $id)
            ->where('sender_user_id', $userId)
            ->with('sender_user', 'receiver_user')             
            ->get();
            return response()->json(['messages' => $messages], 200);
            
        }else{
            echo "Sorry no data found";
        }
        
    }


    public function view_name($id){
        $userName = Profile::select('full_name', 'image')->where('user_id', $id)->first();
        return response()->json(['userName' => $userName], 200);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function send_message(Request $request)
    {
        $userId = Auth::id();
        $receiverId = $request->id;
        $message = $request->message;

        $permission = ChatRequest::where('sender_user_id',$userId)
        ->where('receiver_user_id', $receiverId)
        ->where('status', 1) 
        ->orWhere('receiver_user_id', $userId)
        ->where('sender_user_id', $receiverId)
        ->where('status', 1)
        ->first();

        if($permission){
            $chat = new Chat();
            $chat->sender_user_id = $userId;
            $chat->receiver_user_id = $receiverId;
            $chat->message = $message;
            $chat->created_at = date('Y-m-d');
            $chat->save();
        }
        return response()->json(['message' => $permission], 200); 
        
    }


    public function unread_message(){
        $userId = Auth::id();
        $messages = Chat::where('receiver_user_id',$userId)
            ->where('is_seen', 1) 
            ->distinct('sender_user_id')         
            ->count();
        return response()->json(['messages' => $messages], 200);
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        $deleteResult = Chat::find($id)->delete();
        if($deleteResult){
            Toastr::success('Conversation has deleted.', 'success');
            return response()->json(['message' => 'Ok'], 200);
        }
        
    }
}

app/Http/Controllers/user/ChatRequestController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Brian2694\Toastr\Facades\Toastr;
use App\ChatRequest;
use App\User;
use App\Profile;

class ChatRequestController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index($id)
    {
        $userId = Auth::id();
        $receiverProfileId = (int)$id;

        $receiverId = Profile::select('user_id', 'full_name')->where('id', $id)->first();
    
        $checkRequest = ChatRequest::where('sender_user_id',$userId)
        ->where('receiver_user_id', $receiverId->user_id)
        ->orWhere('receiver_user_id', $userId)
        ->where('sender_user_id', $receiverId->user_id)
        ->first();

        if(is_null($checkRequest)){            
            $chatRequest = new ChatRequest();
            $chatRequest->sender_user_id = $userId;
            $chatRequest->receiver_user_id = $receiverId->user_id;
            $chatRequest->created_at = date('Y-m-d');
            $chatRequest->save();
            addTrail('User has successfully send the chat request to '.$id.'.', 'Success');
            Toastr::success('Your chat request has sent to '.$receiverId->full_name);
            return response()->json(['message' => 'Your chat request has sent to '.$receiverId->full_name], 200);
        }else{                
            if($checkRequest->status == 1){
                Toastr::error('You have already connected with '.$receiverId->full_name);
                return response()->json(['message' => 'You have already connected with '.$receiverId->full_name], 200);
            }else{
                Toastr::error('You have already send the chat request to '.$receiverId->full_name);
                return response()->json(['message' => 'You have already send the chat request to '.$receiverId->full_name], 200);
            }           
            
        }        
    }

    public function notifications(){
        $userId = Auth::id();

        $notifications =  ChatRequest::where('receiver_user_id', $userId)->where('status', 0)->count();

        return response()->json(['notifications' => $notifications], 200);
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function notification_details()
    {
        $userId = Auth::id();
        $notifications =  ChatRequest::where('receiver_user_id', $userId)->where('status', 0)->with('sender_user')->paginate(12);
        
        

        return view('pages.chat.request', ['notifications' => $notifications]);
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function accept_request($id)
    {
        $userId = Auth::id();
        $senderId = Profile::select('user_id', 'full_name')->where('id',$id)->first();

        $update = ChatRequest::where('receiver_user_id', $userId)->where('sender_user_id', $senderId->user_id)->update(['status' => 1]);
        Toastr::success('You have accepted the chat request of '.$senderId->full_name. '. Now you can chat with '.$senderId->full_name);
        return response()->json(['id' => $senderId], 200);
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function denied_request($id)
    {
        $userId = Auth::id();
        $senderId = Profile::select('user_id', 'full_name')->where('id',$id)->first();

        $deleteResult = ChatRequest::where('receiver_user_id', $userId)->where('sender_user_id', $senderId->user_id)->delete();

        if($deleteResult){
            Toastr::success('You have denied the chat request of '.$senderId->full_name);
            return response()->json(['success' => 'Ok'], 200);
        }else{
            Toastr::error('Woops!! Something went wrong, try again');
            return response()->json(['success' => 'Ok'], 200);
        }
    }
}

app/Http/Controllers/user/UserProfileUpdateController.php
<?php

namespace App\Http\Controllers\user;

use Illuminate\Http\Request;
use App\Http\Controllers\Controller;
use Illuminate\Support\Facades\Auth;
use Illuminate\Support\Facades\Input;
use Brian2694\Toastr\Facades\Toastr;
use Intervention\Image\Facades\Image;
use Illuminate\Support\Facades\Storage;
use App\User;
use App\Choice;
use App\Profile;
use App\Country;
use App\District;
use App\Division;
use App\Religion;
use App\Caste;
use App\MaritalStatus;
use App\BloodGroup;
use App\Immigration;
use App\NRB;
use App\Education;
use App\EmployeType;
use App\Occupation;
use App\IncomeRange;
use App\Employment;
use DB;
use Carbon\Carbon;
use File;

class UserProfileUpdateController extends Controller
{
    /**
     * Display a listing of the resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function index()
    {
        $userId = Auth::user()->id;
        $profileId = Profile::select('id')->where('user_id', $userId)->first();
        $profileDetails = Profile::where('id', $profileId->id)
        ->with('country', 'present_district', 'home_district','religion', 'caste', 'occupation', 'employe_type', 'income_range', 'marital_status', 'nrb', 'employment', 'education')
        ->first();
        return view('pages.users.profile.show',['profileDetails' => $profileDetails]);        
    }

    /**
     * Show the form for creating a new resource.
     *
     * @return \Illuminate\Http\Response
     */
    public function create()
    {
        //
    }

    /**
     * Store a newly created resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @return \Illuminate\Http\Response
     */
    public function store(Request $request)
    {
        //
    }

    /**
     * Display the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function show($id)
    {
        //
    }

    /**
     * Show the form for editing the specified resource.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function edit($id)
    {
        //
    }

    /**
     * Update the specified resource in storage.
     *
     * @param  \Illuminate\Http\Request  $request
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function update(Request $request, $id)
    {
        //
    }

    /**
     * Remove the specified resource from storage.
     *
     * @param  int  $id
     * @return \Illuminate\Http\Response
     */
    public function destroy($id)
    {
        //
    }
}

resources/views/pages/users/choice/show.blade.php
@extends('layouts.user')
@section('title', 'Preferences')
@section('sliderText', 'Your Preferences')

@section('content')
<div class="whole-wrap">
    <div class="container"> 
                 
        <!--Start of Wizard Area-->
        <div class="container-fluid">
          <div class="row">
            <div class="col-xs-12 col-md-8 offset-md-2">
              <div class="wizard card-like">                
                  <div class="wizard-header">
                    <div class="row">
                      <div class="col-md-12 col-xs-12">
                        <h3 class="text-center">Your Preferences<br><small></small></h3>
                      </div>
                    </div>
                  </div>
                  
                  <div class="wizard-body">
                    <div class="step initial active">                     
                      <div class="row">                       
                        <div class="col-lg-12 col-md-12 col-xs-12">                    
                        <form action="#" method="POST" class="from_registration">    
                                @csrf                                                                              
                              <div class="mt-10">
                                <div class="form-select">
                                    <input type="text"  class="religion_select" value="@if(!empty($choice->age_from)){{ 'From age: '.$choice->age_from. ' years' }}@endif" readonly="readonly">                                    
                                 </div>
                              </div>              
                              <div class="mt-10">
                                <div class="form-select">
                                    <input type="text"  class="religion_select" value="@if(!empty($choice->age_to)){{ 'To age: '.$choice->age_to. ' years' }}@endif" readonly="readonly">
                                 </div>
                              </div> 
                              <div class="mt-10">
                                    <div class="form-select" id="default-select">
                                        <input type="text"  class="religion_select" value="@if(!empty($choice->height_from)){{ 'From Height: '.inches2feet($choice->height_from) }}@endif" readonly="readonly">
                                    </div>
                                </div>
                                <div class="mt-10">
                                    <div class="form-select" id="default-select">
                                        <input type="text"  class="religion_select" value="@if(!empty($choice->height_to)){{ 'To height: '.inches2feet($choice->height_to) }}@endif" readonly="readonly">
                                    </div>
                              </div>                                                                                 
                              <div class="mt-10">
                                    <div class="form-select">                                        
                                        <input type="text"  class="religion_select" value="@if(!empty($choice->marital_status->english_name)){{ 'Marital Status: '.$choice->marital_status->english_name }}@endif" readonly="readonly">                                        
                                    </div>
                                </div> 
                                <div class="mt-10">
                                    <div class="form-select">
                                        <input type="text"  class="religion_select" value="@if(!empty($choice->division->english_name)){{ 'Division: '.$choice->division->english_name }}@endif" readonly="readonly">
                                    </div>
                                </div>                    
                                <div class="mt-10">
                                    <div class="form-select">
                                        <input type="text"  class="religion_select" value="@if(!empty($choice->education->english_name)){{ 'Education: '.$choice->education->english_name }}@endif" readonly="readonly">
                                    </div>
                                </div>
                                  
                                <div class="mt-10">
                                    <div class="form-select">
                                        <input type="text"  class="religion_select" value="@if(!empty($choice->employe_type->english_name)){{ 'Employment type: '.$choice->employe_type->english_name }}@endif" readonly="readonly">
                                    </div>
                                </div>                 
                                <div class="mt-10">
                                    <div class="form-select">
                                        <input type="text"  class="religion_select" value="@if(!empty($choice->occupation->english_name)){{ 'Occupation: '.$choice->occupation->english_name }}@endif" readonly="readonly">
                                    </div>
                                </div>                                                             
                                <div class="mt-10">
                                    <div class="form-select">
                                        <input type="text"  class="religion_select" value="@if(!empty($choice->income_range->en_range_from)){{ 'Income Range: '.$choice->income_range->en_range_from }} - {{ $choice->income_range->en_range_to }} @endif" readonly="readonly">
                                    </div>
                                </div>                            
                        </div>                        
                      </div>                      
                    </div>   
                  </div>
                  
                  <div class="wizard-footer">
                    <div class="row">                      
                      <div class="col-xs-6 pull-right text-center">
                        <a href="{{route('user.dashboard')}}"  name="submit" class="step-btn modal-ticker-btn">Back</a>
                        <a href="{{route('user.choice.edit', $choice->id)}}" class="step-btn modal-ticker-btn">Edit</a>
                      </div>
                    </div>
                  </div>
                  
                </form>
              </div>
            </div>
          </div>
        </div>    
        <!--Start of Wizard Area-->       
    </div>
</div>
@endsection

@push('js')
<script type="text/javascript">
    //hide show
    $(function () {
        //Marital status
        $('#marital_status').change(function () {
            var select=$(this).find(':selected').val();        
            $(".has-child").hide("slow");
            $('#' + select).show("slow");
        }).change();
        //Marital status
        
        //Religion select
        $('.religion_select').change(function () {
            var select=$(this).find(':selected').val();        
            $(".religiontik").hide("slow");
            $(".hindutik").hide("slow");
            $('#' + select).show("slow");
        }).change();
        //Religion select
        
        //country select
        $('.country-bd-select').change(function () {
            var select=$(this).find(':selected').val(); 
            $(".bd-district").hide("slow");
            $(".bd-adress-area").hide("slow");
            $('#' + select).show("slow");
        }).change();
        $('.dis_select').change(function () {
            var select=$(this).find(':selected').val(); 
            $(".bd-adress-area").hide("slow");
            $('#' + select).show("slow");
        }).change(); 
        
        $('.country-ame-select').on('change', function() {
          $('.ame-state').css('display', 'none');
          if ( $(this).val() === 'ame' ) {
            $('.ame-state').slideToggle().css('display', 'block');
          }
        });
    
        $('.origin-select').change(function () {
            var select=$(this).find(':selected').val(); 
            $(".home-origin").hide("slow");
            $('#' + select).show("slow");
        }).change(); 
    
        $('.education-level').change(function () {
            var select=$(this).find(':selected').val(); 
            $(".edu-detail").hide("slow");
            $('#' + select).show("slow");
        }).change();  
    
        $('.emp-in').change(function () {
            var select=$(this).find(':selected').val(); 
            $(".other-emp-area").hide("slow");
            $('#' + select).show("slow");
        }).change();  
    
        $('.occ').change(function () {
            var select=$(this).find(':selected').val(); 
            $(".other-occ-area").hide("slow");
            $('#' + select).show("slow");
        }).change(); 
        //country select 
        
    });
    //hide show        
    
    //Wizard area Js
    $(document).ready(function () {
    // Checking button status ( wether or not next/previous and
    // submit should be displayed )
    const checkButtons = (activeStep, stepsCount) => {
      const prevBtn = $("#wizard-prev");
      const nextBtn = $("#wizard-next");
      const submBtn = $("#wizard-subm");

      switch (activeStep / stepsCount) {
        case 0: // First Step
          prevBtn.hide();
          submBtn.hide();
          nextBtn.show();
          break;
        case 1: // Last Step
          nextBtn.hide();
          prevBtn.show();
          submBtn.show();
          break;
        default:
          submBtn.hide();
          prevBtn.show();
          nextBtn.show();
      }
    };
    // Scrolling the form to the middle of the screen if the form
    // is taller than the viewHeight
    const scrollWindow = (activeStepHeight, viewHeight) => {
      if (viewHeight < activeStepHeight) {
        $(window).scrollTop($(steps[activeStep]).offset().top - viewHeight / 2);
      }
    };
    // Setting the wizard body height, this is needed because
    // the steps inside of the body have position: absolute
    const setWizardHeight = activeStepHeight => {
      $(".wizard-body").height(activeStepHeight);
    };
    $(function() {
      // Form step counter (little cirecles at the top of the form)
      const wizardSteps = $(".wizard-header .wizard-step");
      // Form steps (actual steps)
      const steps = $(".wizard-body .step");
      // Number of steps (counting from 0)
      const stepsCount = steps.length - 1;
      // Screen Height
      const viewHeight = $(window).height();
      // Current step being shown (counting from 0)
      let activeStep = 0;
      // Height of the current step
      let activeStepHeight = $(steps[activeStep]).height();
      checkButtons(activeStep, stepsCount);
      setWizardHeight(activeStepHeight);
      // Resizing wizard body when the viewport changes
      $(window).resize(function() {
        setWizardHeight($(steps[activeStep]).height());
      });
      // Previous button handler
      $("#wizard-prev").click(() => {
        // Sliding out current step
        $(steps[activeStep]).removeClass("active");
        $(wizardSteps[activeStep]).removeClass("active");
        activeStep--;
        // Sliding in previous Step
        $(steps[activeStep]).removeClass("off").addClass("active");
        $(wizardSteps[activeStep]).addClass("active");

        activeStepHeight = $(steps[activeStep]).height();
        setWizardHeight(activeStepHeight);
        checkButtons(activeStep, stepsCount);
      });
      // Next button handler
      $("#wizard-next").click(() => {
        // Sliding out current step
        $(steps[activeStep]).removeClass("inital").addClass("off").removeClass("active");
        $(wizardSteps[activeStep]).removeClass("active");
        // Next step
        activeStep++;
        // Sliding in next step
        $(steps[activeStep]).addClass("active");
        $(wizardSteps[activeStep]).addClass("active");

        activeStepHeight = $(steps[activeStep]).height();
        setWizardHeight(activeStepHeight);
        checkButtons(activeStep, stepsCount);
      });
    });    
    });

    //Wizard area Js    
</script>
@endpush